//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBankProgect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kredit
    {
        public Kredit(int accauntNumber, int money, int deposite)
        {
            AccauntNumber = accauntNumber;
            Money = money;
            Deposite = deposite;
        }

        public int Deposite { get; set; }
        public int Id { get; set; }
        public int AccauntNumber { get; set; }
        public int Money { get; set; }
    }
}
